# Generated by Django 4.2.5 on 2024-01-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='conversatiopn',
            new_name='conversation',
        ),
    ]
